Imported Upstream version 5.0.6-dfsg

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -153,12 +153,19 @@ PKGCONFIG="`which_wrapper pkg-config`"
 PYTHONDIR="/usr /usr/local"
 QT4DIR="/usr/lib/qt4 /usr/share/qt4 /usr/lib64/qt4 /usr /usr/local"
 QT4DIR_PKGCONFIG=1
-QT4UIC3DIR="/usr/bin"
 KBUILDDIR="`cd \`dirname $0\`; pwd`/kBuild"
 DEVDIR="`cd \`dirname $0\`; pwd`/tools"
 if [ -d "/lib/modules/`uname -r`/build" ]; then
- LINUX="/lib/modules/`uname -r`/build"
-else
+  LINUX="/lib/modules/`uname -r`/build"
+elif [ "`echo /lib/modules/*`" != "/lib/modules/*" ]; then
+  # Get the most recent kernel headers if none match the current kernel.
+  for i in /lib/modules/*; do
+    if [ -r "$i/build" ]; then
+      LINUX="$i/build"
+    fi
+  done
+fi
+if [ -z "$LINUX" ]; then
  LINUX="/usr/src/linux"
 fi
 KCHMVIEWER="kchmviewer"
@@ -317,12 +324,18 @@ test_execute()
 # Execute a compiled test binary
 test_execute_path()
 {
+  ## LD_LIBRARY_PATH to set.
+  local_path="${1}"
+  ## Set this to non-empty to make this test non-fatal.
+  local_nofail="${2}"
   echo "executing the binary (LD_LIBRARY_PATH=$1)" >> $LOG
-  LD_LIBRARY_PATH=$1 $ODIR.tmp_out > $ODIR.test_execute.log
+  LD_LIBRARY_PATH="${local_path}" $ODIR.tmp_out > $ODIR.test_execute.log
   rc=$?
   cat $ODIR.test_execute.log | tee -a $LOG
   if [ $rc -ne 0 ]; then
-    fail
+    test -z "${local_nofail}" && fail
+    echo >> $LOG
+    echo >> $LOG
     return 1
   fi
   echo >> $LOG
@@ -422,9 +435,9 @@ check_gcc()
              -o \( $cc_maj -eq 3 -a $cc_min -lt 2 \) \
              -o \( $cc_maj -eq 4 -a $cc_min -lt 1 -a "$OS" != "darwin" \) \
              -o \( $cc_maj -eq 4 -a $cc_min -gt 9 \) \
-             -o \( $cc_maj -eq 5 -a $cc_min -gt 1 \) \
+             -o \( $cc_maj -eq 5 -a $cc_min -gt 2 \) \
              -o $cc_maj -gt 5 ]; then
-        log_failure "gcc version $cc_maj.$cc_min found, expected gcc 3.x with x>1 or gcc 4.x with 0<x<10 or gcc 5.1"
+        log_failure "gcc version $cc_maj.$cc_min found, expected gcc 3.x with x>1 or gcc 4.x with 0<x<10 or gcc 5.2"
         fail really
       else
         log_success "found version $cc_ver"
@@ -1134,7 +1147,7 @@ EOF
       fi
     fi
   else
-    log_failure "SDL not found"
+    log_failure "SDL not found (can be disabled using --disable-sdl)"
     fail
   fi
 }
@@ -1450,24 +1463,35 @@ check_qt4()
 {
   foundqt4=
   test_header Qt4
+  cat > $ODIR.tmp_src.cc << EOF
+#include <QtGlobal>
+extern "C" int main(void)
+{
+#if QT_VERSION >= 0x040800
+  return 0;
+#else
+  return 1;
+#endif
+}
+EOF
   if [ "$OS" = "darwin" ]; then
     # First check if there is the internal version of Qt. If yes nothing else
     # has to be done.
     QT_INTERNAL=`/bin/ls -rd1 $PWD/tools/$BUILD_TARGET.$BUILD_PLATFORM_ARCH/qt/* 2> /dev/null`
     for t in $QT_INTERNAL; do
-        if [ -f "$t/Frameworks/QtCoreVBox.framework/QtCoreVBox" ]; then
-          cnf_append "VBOX_WITH_QT4_SUN" "1"
-          log_success "use internal version"
-          return
-        fi
+      if [ -f "$t/Frameworks/QtCoreVBox.framework/QtCoreVBox" ]; then
+        cnf_append "VBOX_WITH_QT4_SUN" "1"
+        log_success "use internal version"
+        return
+      fi
     done
     # Now try the user provided directory and some of the standard directories.
     QT_TRIES="$QT4DIR /System/Library /Library"
     for t in $QT_TRIES; do
-        if [ -f "$t/Frameworks/QtCore.framework/QtCore" ]; then
-          PATH_SDK_QT4="$t"
-          break
-        fi
+      if [ -f "$t/Frameworks/QtCore.framework/QtCore" ]; then
+        PATH_SDK_QT4="$t"
+        break
+      fi
     done
     # Add the necessary params for building the test application
     if [ -n "$PATH_SDK_QT4" ]; then
@@ -1479,67 +1503,51 @@ check_qt4()
       log_failure "Qt4 framework not found (can be disabled using --disable-qt4)"
       fail
     fi
-  else
+  else # !darwin
     if [ $QT4DIR_PKGCONFIG -eq 1 ]; then
       # default is to use pkg-config
       if which_wrapper pkg-config > /dev/null; then
-        # this braindead path is necessary for mdv2008.1
-        qt4_ver=`\
-            PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/qt4/lib/pkgconfig \
-            pkg-config QtCore --modversion 2>> $LOG`
-        if [ $? -ne 0 ]; then
-          log_failure "QtCore not found"
-          fail
-        else
-          FLGQT4=`\
-              PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/qt4/lib/pkgconfig \
-              pkg-config QtCore --cflags`
+        qt4_ver=`pkg-config QtCore --modversion 2>> $LOG`
+        if [ $? -eq 0 ]; then
+          FLGQT4=`pkg-config QtCore --cflags`
           INCQT4=`strip_I "$FLGQT4"`
-          LIBQT4=`\
-              PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/qt4/lib/pkgconfig \
-              PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 \
-              pkg-config QtCore --libs`
-          foundqt4=1
+          LIBQT4=`PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 pkg-config QtCore --libs`
+          TOOLQT4=`pkg-config QtCore --variable=prefix`
+          TOOLQT4MOC="`pkg-config QtCore --variable=moc_location`"
+          TOOLQT4BIN="`dirname $TOOLQT4MOC`"
+          if test_compile "$LIBQT4 $LIBPTHREAD $I_INCQT4 $FLGQT4" qt4 qt4 nofatal; then
+            test_execute_path "`strip_L "$LIBQT4"`" nofatal && foundqt4=3 # pkg-config
+          fi
         fi
       else
         log_failure "pkg-config not found"
         fail
       fi
-    else
+    fi
+    if [ -z "$foundqt4" ]; then
       # do it the old way (e.g. user has specified QT4DIR)
-      cat > $ODIR.tmp_src.cc << EOF
-#include <cstdio>
-#include <QtGlobal>
-extern "C" int main(void)
-{
-  printf("found version %s", QT_VERSION_STR);
-#if QT_VERSION >= 0x040800
-  printf(", OK.\n");
-  return 0;
-#else
-  printf(", expected version 4.8.0 or higher\n");
-  return 1;
-#endif
-}
-EOF
-      for q in $QT4DIR; do
+      for q in $QT4DIR "$PWD/tools/linux.$TARGET_MACHINE"/qt/v4.8.*; do
         INCQT4="$q/include $q/include/QtCore"
         FLGQT4="-DQT_SHARED"
         I_INCQT4=`prefix_I "$INCQT4"`
         LIBQT4="-L$q/lib -lQtCoreVBox"
-        if test_compile "$LIBQT4 $LIBPTHREAD $I_INCQT4 $FLGQT4" qt4 qt4 nofatal; then
-          foundqt4=2
+        TOOLQT4="$q"
+        if test_compile "$LIBQT4 $LIBPTHREAD $I_INCQT4 $FLGQT4" qt4 qt4 nofatal &&
+            test_execute_path "`strip_L "$LIBQT4"`" nofatal; then
+          foundqt4=2 # internal
           break;
         fi
         LIBQT4="-L$q/lib -lQtCore"
-        if test_compile "$LIBQT4 $LIBPTHREAD $I_INCQT4 $FLGQT4" qt4 qt4 nofatal; then
-          foundqt4=1
+        if test_compile "$LIBQT4 $LIBPTHREAD $I_INCQT4 $FLGQT4" qt4 qt4 nofatal &&
+            test_execute_path "`strip_L "$LIBQT4"`" nofatal; then
+          foundqt4=1 # no pkg-config, Qt directory
           break;
         fi
       done
     fi
   fi
   if [ -n "$foundqt4" ]; then
+    # we decided which version of Qt to use. Now enforce the version requirement
     cat > $ODIR.tmp_src.cc << EOF
 #include <cstdio>
 #include <QtGlobal>
@@ -1568,7 +1576,6 @@ EOF
           # directories.
           for q in $PATH_SDK_QT4 /usr /Developer/Tools/Qt; do
             if which_wrapper "$q/bin/moc" > /dev/null; then
-              cnf_append "PATH_TOOL_QT4" "$q"
               cnf_append "PATH_TOOL_QT4_BIN" "$q/bin"
             fi
           done
@@ -1579,45 +1586,35 @@ EOF
           # most likely pkg-config gave us -I/usr/include/qt4 -I/usr/include/qt4/QtCore
           INCQT4=`echo "$INCQT4"|$KBUILD_SED 's|\([^ ]*\) .*|\1|'`
           cnf_append "VBOX_PATH_QT4_LIB" "`strip_L "$LIBQT4"`"
-          cnf_append "SDK_QT4_LIBPATH" "`strip_L "$LIBQT4"`"
           cnf_append "PATH_SDK_QT4_INC" "$INCQT4"
           # this is not quite right since the qt libpath does not have to be first...
           cnf_append "PATH_SDK_QT4_LIB" '$'"(firstword `strip_L "$LIBQT4"`)"
           if [ "$foundqt4" = "2" ]; then
             cnf_append "VBOX_WITH_QT4_SUN" "1"
+          elif [ "$foundqt4" = "3" ]; then
+            cnf_append "VBOX_PATH_QT4" "$TOOLQT4"
+            cnf_append "PATH_SDK_QT4" "$TOOLQT4"
+            cnf_append "PATH_TOOL_QT4_BIN" "$TOOLQT4BIN"
+            return
           fi
           test_header "Qt4 devtools"
-          for q in $QT4DIR; do
-            # first try it with a suffix, some platforms use that
-            if which_wrapper "$q/bin/moc-qt4" > /dev/null; then
-              moc_ver=`$q/bin/moc-qt4 -v 2>&1|sed 's+^.*(Qt \(.*\))+\1+'`
-              if [ $? -ne 0 ]; then
-                log_failure "moc-qt4 not working"
-                fail
-              else
-                log_success "found version $moc_ver"
-                cnf_append "VBOX_PATH_QT4" "$q"
-                cnf_append "PATH_SDK_QT4" "$q"
-                cnf_append "PATH_TOOL_QT4" "$q"
-                cnf_append "PATH_TOOL_QT4_BIN" "$q/bin"
-                cnf_append "TOOL_QT4_BIN_SUFF" "-qt4"
-                return
-              fi
-            elif which_wrapper "$q/bin/moc" > /dev/null; then
-              moc_ver=`$q/bin/moc -v 2>&1|sed 's+^.*(Qt \(.*\))+\1+'`
-              if [ $? -ne 0 ]; then
-                log_failure "moc not working"
-                fail
-              else
-                log_success "found version $moc_ver"
-                cnf_append "VBOX_PATH_QT4" "$q"
-                cnf_append "PATH_SDK_QT4" "$q"
-                cnf_append "PATH_TOOL_QT4" "$q"
-                cnf_append "PATH_TOOL_QT4_BIN" "$q/bin"
-                return
-              fi
-            fi
-          done
+          # try it with a suffix, some platforms use that
+          if which_wrapper "$TOOLQT4/bin/moc-qt4" > /dev/null; then
+            QT4BINSUFF="-qt4"
+          else
+            QT4BINSUFF=""
+          fi
+          moc_ver=`$TOOLQT4/bin/moc$QT4BINSUFF -v 2>&1|sed 's+^.*(Qt \(.*\))+\1+'`
+          if [ $? -ne 0 ]; then
+            log_failure "moc$QT4BINSUFF not working"
+            fail
+          else
+            log_success "found version $moc_ver"
+            cnf_append "VBOX_PATH_QT4" "$TOOLQT4"
+            cnf_append "PATH_SDK_QT4" "$TOOLQT4"
+            cnf_append "PATH_TOOL_QT4_BIN" "$TOOLQT4/bin"
+            [ -n "$QT4BINSUFF" ] && cnf_append "TOOL_QT4_BIN_SUFF" "$QT4BINSUFF"
+          fi
         fi
       fi
     else
@@ -1629,6 +1626,7 @@ EOF
     fail
   fi
 }
+
 
 #
 # Check for libvpx
@@ -2513,6 +2511,9 @@ for option in "$@"; do
     --disable-libvpx)
       WITH_LIBVPX=0
       ;;
+    --disable-vboxsdl)
+      WITH_SDL=0
+      ;;
     --build-debug|-d)
       BUILD_TYPE=debug
       ;;
@@ -2720,7 +2721,11 @@ if [ $ONLY_ADDITIONS -eq 0 ]; then
  [ "$OS" != "darwin"  ] && check_z
   [ "$OS" != "darwin"  ] && check_png
   [ $OSE -eq 0 -a "$OS" = "linux" ] && check_pam
-  [ $WITH_SDL -eq 1 ]    && check_sdl
+  if [ $WITH_SDL -eq 1 ]; then
+    check_sdl
+  else
+    cnf_append "VBOX_WITH_VBOXSDL" ""
+  fi
   [ $WITH_SDL_TTF -eq 1 -a $OSE -eq 0 ] && check_sdl_ttf
   [ $WITH_X11    -eq 1 ] && check_x
   # TODO check for xcomposite-dev (X11/extensions/Xcomposite.h, additions only)
