Adapted patches and installation files for new upstream version. 16-no-update.dpatch was deactivated for now because it has to be re-implemented.

diff --git a/debian/virtualbox-ose-guest-utils.init b/debian/virtualbox-ose-guest-utils.init
--- a/debian/virtualbox-ose-guest-utils.init
+++ b/debian/virtualbox-ose-guest-utils.init
@@ -2,7 +2,7 @@
 # (C) 2007 Michael Meskes <meskes@debian.org>
 
 ### BEGIN INIT INFO
-# Provides:          vboxadd virtualbox-ose-guest-utils
+# Provides:          vboxguest virtualbox-ose-guest-utils
 # Short-Description: VirtualBox Linux Additions
 # Required-Start:    $remote_fs
 # Required-Stop:     $remote_fs
@@ -37,10 +37,10 @@ case "$1" in
 	log_begin_msg "Starting VirtualBox Additions"
 
 	# should already be loaded automatically
-	if ! running vboxadd; then
-		if ! modprobe vboxadd > /dev/null 2>&1; then
-			# vboxadd not installed, or has a problem
-			log_failure_msg "Guest additions not available, kernel module not loadable (vboxadd)"
+	if ! running vboxguest; then
+		if ! modprobe vboxguest > /dev/null 2>&1; then
+			# vboxguest not installed, or has a problem
+			log_failure_msg "Guest additions not available, kernel module not loadable (vboxguest)"
 			log_end_msg 1
 			exit 1
 		fi
@@ -88,9 +88,9 @@ case "$1" in
 		fi
 	fi
 
-	if running vboxadd; then
-		if ! rmmod vboxadd 2>/dev/null; then
-			log_failure_msg "Cannot unload guest additions kernel module (vboxadd)"
+	if running vboxguest; then
+		if ! rmmod vboxguest 2>/dev/null; then
+			log_failure_msg "Cannot unload guest additions kernel module (vboxguest)"
 			log_end_msg 1
 			exit 1
 		fi
@@ -106,8 +106,8 @@ case "$1" in
   status)
 	status=0
 
-	if ! running vboxadd; then
-		echo "Guest additions kernel module (vboxadd) not loaded"
+	if ! running vboxguest; then
+		echo "Guest additions kernel module (vboxguest) not loaded"
 		status=3
 	fi
 
