Applied patch by Kel Modderman.

diff --git a/debian/virtualbox-ose-guest-utils.init b/debian/virtualbox-ose-guest-utils.init
--- a/debian/virtualbox-ose-guest-utils.init
+++ b/debian/virtualbox-ose-guest-utils.init
@@ -14,23 +14,40 @@ PATH=$PATH:/bin:/sbin:/usr/sbin
 
 . /lib/lsb/init-functions
 
-set -e
+in_virtual_machine()
+{
+	if [ -z "$(lspci -d 80ee:beef)" ]; then
+		log_action_begin_msg 'VirtualBox Additions Disabled';
+		log_warning_msg 'not in a Virtual Machine environemnt';
+		log_end_msg 0
+		return 1
+	fi
 
-(lspci|grep -q 80ee:beef) || exit 0 # not inside a vm
+	return 0
+}
 
 case "$1" in
   start)
+  	in_virtual_machine || exit 0
   	log_action_begin_msg 'Starting VirtualBox Additions';
-	# udev should have already handled thismodule
-	# modprobe vboxadd
+	# udev should have already handled this module
+	# double check kernel support is present or die
+	modprobe --quiet vboxadd
+	if [ "$?" -ne 0 ]; then
+		# vboxadd not installed, or has a problem
+		log_failure_msg 'cannot modprobe vboxadd kernel module';
+		log_end_msg 1
+		exit 1
+	fi
 
 	start-stop-daemon --start --quiet --exec /usr/sbin/vboxadd-timesync -- --daemonize
-	log_end_msg 0
+	log_end_msg $?
 	;;
   stop)
+  	in_virtual_machine || exit 0
   	log_action_begin_msg 'Stopping VirtualBox Additions';
 	start-stop-daemon --stop --quiet --oknodo --exec /usr/sbin/vboxadd-timesync
-	log_end_msg 0
+	log_end_msg $?
 	;;
   restart|force-reload)
 	#
