Unload vboxsf kernel module on stop.

diff --git a/debian/virtualbox-ose-guest-utils.init b/debian/virtualbox-ose-guest-utils.init
--- a/debian/virtualbox-ose-guest-utils.init
+++ b/debian/virtualbox-ose-guest-utils.init
@@ -65,6 +65,14 @@ case "$1" in
 		exit 1
 	fi
 
+	if running vboxsf; then
+		if ! rmmod vboxsf 2>/dev/null; then
+			log_failure_msg "Cannot unload shared folders kernel module (vboxsf)"
+			log_end_msg 1
+			exit 1
+		fi
+	fi
+
 	if running vboxguest; then
 		if ! rmmod vboxguest 2>/dev/null; then
 			log_failure_msg "Cannot unload guest additions kernel module (vboxguest)"
