Use a common coding style in all maintainer scripts.

diff --git a/debian/virtualbox-ose.preinst b/debian/virtualbox-ose.preinst
--- a/debian/virtualbox-ose.preinst
+++ b/debian/virtualbox-ose.preinst
@@ -6,40 +6,40 @@ set -e
 
 # Remove a no-longer used conffile
 rm_conffile() {
-    PKGNAME="$1"
-    CONFFILE="$2"
-    if [ -e "$CONFFILE" ]; then
-        md5sum="`md5sum \"$CONFFILE\" | sed -e \"s/ .*//\"`"
-        old_md5sum="`dpkg-query -W -f='${Conffiles}' $PKGNAME | sed -n -e \"\\\\' $CONFFILE '{s/ obsolete$//;s/.* //p}\"`"
-        if [ "$md5sum" != "$old_md5sum" ]; then
-            echo "Obsolete conffile $CONFFILE has been modified by you."
-            echo "Saving as $CONFFILE.dpkg-bak ..."
-            mv -f "$CONFFILE" "$CONFFILE".dpkg-bak
-        else
-	    echo "Removing obsolete conffile $CONFFILE ..."
-	    rm -f "$CONFFILE"
-        fi
-    fi
+	PKGNAME="$1"
+	CONFFILE="$2"
+	if [ -e "$CONFFILE" ]; then
+		md5sum="`md5sum \"$CONFFILE\" | sed -e \"s/ .*//\"`"
+		old_md5sum="`dpkg-query -W -f='${Conffiles}' $PKGNAME | sed -n -e \"\\\\' $CONFFILE '{s/ obsolete$//;s/.* //p}\"`"
+		if [ "$md5sum" != "$old_md5sum" ]; then
+			echo "Obsolete conffile $CONFFILE has been modified by you."
+			echo "Saving as $CONFFILE.dpkg-bak ..."
+			mv -f "$CONFFILE" "$CONFFILE".dpkg-bak
+		else
+			echo "Removing obsolete conffile $CONFFILE ..."
+			rm -f "$CONFFILE"
+		fi
+	fi
 }
 
 case "$1" in
   install|upgrade)
-    rm_conffile virtualbox-ose /etc/network/if-post-down.d/virtualbox-ose
-    rm_conffile virtualbox-ose /etc/network/if-pre-up.d/virtualbox-ose
-    rm_conffile virtualbox-ose /etc/vbox/interfaces
+	rm_conffile virtualbox-ose /etc/network/if-post-down.d/virtualbox-ose
+	rm_conffile virtualbox-ose /etc/network/if-pre-up.d/virtualbox-ose
+	rm_conffile virtualbox-ose /etc/vbox/interfaces
 
-    # Remove /etc/vbox/vbox.cfg
-    if dpkg --compare-versions "$2" lt "2.2.2-dfsg-3"; then
-      rm_conffile virtualbox-ose /etc/vbox/vbox.cfg
-    fi
+	# Remove /etc/vbox/vbox.cfg
+	if dpkg --compare-versions "$2" lt "2.2.2-dfsg-3"; then
+		rm_conffile virtualbox-ose /etc/vbox/vbox.cfg
+	fi
 
-    # Remove vboxusers group
-    if dpkg --compare-versions "$2" lt "3.0.8-dfsg-1"; then
-      if [ -x /usr/sbin/delgroup ]; then
-        # delgroup may return error status 3 if there is a non-system group
-        # "vboxusers". The postrm should not fail in this case!
-        delgroup --quiet --system vboxusers || true
-      fi
-    fi
+	# Remove vboxusers group
+	if dpkg --compare-versions "$2" lt "3.0.8-dfsg-1"; then
+		if [ -x /usr/sbin/delgroup ]; then
+			# delgroup may return error status 3 if there is a non-system group
+			# "vboxusers". The postrm should not fail in this case!
+			delgroup --quiet --system vboxusers || true
+		fi
+	fi
   ;;
 esac
